version:  '3.2'

services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
    restart: unless-stopped
    ports:
      - "5432:5432"

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret


#docker run --name pgT -p 5432:5432 -e POSTGRES_PASSWORD=testing -d postgres:11-alpine
#docker pull dpage/pgadmin4
#docker run -p 5050:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=secret" dpage/pgadmin4

