version:  '3.2'

services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./pgAdmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

#docker run --name pgT -p 5432:5432 -e POSTGRES_PASSWORD=testing -d postgres:11-alpine
#docker pull dpage/pgadmin4
#docker run -p 5050:80 -e "PGADMIN_DEFAULT_EMAIL=user@domain.com" -e "PGADMIN_DEFAULT_PASSWORD=secret" dpage/pgadmin4

